CREATE TABLE "ESHOP"."CART" 
   (	"EMAIL" VARCHAR2(100 BYTE) primary key, 
	"PRODUCT_ID" NUMBER(10,0), 
	"QUANTITY" NUMBER(5,0), 
	"PRICE" NUMBER(10,2), 
	"TOTAL" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"MOBILENUMBER" VARCHAR2(20 BYTE), 
	"ORDERDATE" DATE, 
	"DELIVERYDATE" DATE, 
	"PAYMENTMETHOD" VARCHAR2(100 BYTE), 
	"TRANSACTIONID" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(10 BYTE)
   ) ;

CREATE TABLE "ESHOP"."MANAGERS" 
   (	"ID" NUMBER(5,0) primary key, 
	"NAME" VARCHAR2(500 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("EMAIL")
   );
CREATE TABLE "ESHOP"."MESSAGE" 
   (	"ID" NUMBER(5,0) primary key, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"SUBJECT" VARCHAR2(200 BYTE), 
	"BODY" VARCHAR2(1000 BYTE), 
	 PRIMARY KEY ("ID")
);
CREATE TABLE "ESHOP"."PRODUCT" 
   (	"ID" NUMBER(5,0) primary key, 
	"NAME" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER(10,0), 
	"ACTIVE" VARCHAR2(10 BYTE)
   );
CREATE TABLE "ESHOP"."USERS" 
   (	"NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MOBILENUMBER" VARCHAR2(50 BYTE), 
	"SECURITYQUESTIONS" VARCHAR2(200 BYTE), 
	"ANSWER" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"WALLET" NUMBER(10,0), 
	 PRIMARY KEY ("EMAIL")
);